// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180416205128_addOutputCheckItem")]
    partial class addOutputCheckItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Checklist", b =>
                {
                    b.Property<int>("ChecklistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("ChecklistId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("Domain.OutputCheckItem", b =>
                {
                    b.Property<int>("OutputCheckItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChecklistId");

                    b.Property<string>("Description");

                    b.Property<string>("IpAddress");

                    b.Property<bool>("NormallyHigh");

                    b.Property<int>("Number");

                    b.Property<string>("State");

                    b.HasKey("OutputCheckItemId");

                    b.HasIndex("ChecklistId");

                    b.ToTable("OutputCheckItems");
                });

            modelBuilder.Entity("Domain.OutputCheckItem", b =>
                {
                    b.HasOne("Domain.Checklist", "Checklist")
                        .WithMany("OutputCheckItems")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
